### ISSUE TITLE
the lights don't work at all in the 1.16.1 version.

### ISSUE THREAD

**Issue by screret** [Flanks255/simplylight#15] opened 2020-07-29 07:21 UTC
**Describe the bug**
they just don't emit light.

**Screenshots**
![2020-07-29_10 17 53](https://user-images.githubusercontent.com/68943070/88769445-14521280-d185-11ea-8751-9982c9a5a2eb.png)

**Comment by Flanks255** [comment] 2020-07-29 11:57
So, im not sure how, i just re-tested all the light blocks, and they work just fine.
Whats around it?

**Comment by screret** [comment] 2020-07-29 15:41
> So, im not sure how, i just re-tested all the light blocks, and they work just fine.
> Whats around it?

darkness?

**Comment by Flanks255** [comment] 2020-07-29 15:43
I mean, what blocks.
what other mods are installed? is that the overworld? nether? end? modded dimension?
what version of forge?

**Comment by screret** [comment] 2020-07-29 15:49
that's the overworld, i have the latest version of forge, in my mods folder i have this mod, worldedit, mekanism, biomes o' plenty, quark and ma essentials. forgot to mention this is on a server.

**Comment by Flanks255** [comment] 2020-07-29 16:10
do they work anywhere? or just 1 spot? because they work fine in every 1.16 instance i spin up...

**Comment by screret** [comment] 2020-07-30 06:19
they don't work anywhere.

**Comment by screret** [comment] 2020-07-30 07:50
oh do i _absolutely_ need the kotlin language adapter

**Comment by Flanks255** [comment] 2020-07-30 08:03
No, that's only for the 1.12 version, I'm at a total loss as to why this
doesn't work in your game... Do torches work? Glows stone blocks?

**Comment by screret** [comment] 2020-07-30 08:05
everything else works, just not these.

**Comment by Flanks255** [comment] 2020-07-30 08:55
Could you post a screenshot with the f3 debug screen on, preferably with
the cross hair aimed at the light.

**Comment by trey-k** [comment] 2020-07-30 20:38
Was having the same problem but realized I was wearing the miners helmet, lights worked when reloading the game until going beneath them equipping the helmet, the light does not come back on. Took off the helmet and things are working great, seems to be a fight for the lighting control, optifines dynamic lighting works fine here

**Comment by Flanks255** [comment] 2020-07-30 20:40
Thats interesting... what mod is the mining helmet from?

**Comment by trey-k** [comment] 2020-07-30 20:50
It's a standalone mod called [Miner's Helmet](https://www.curseforge.com/minecraft/mc-mods/miners-helmet)

**Comment by Buttplucc** [comment] 2020-07-30 21:58
My lights also do not work in 1.16.1. Light does not come out of any of them. I tested the illuminant block to see if it would turn on and off, which it did when placed next to redstone, but it does not make light

**Comment by Flanks255** [comment] 2020-07-30 22:12
could all of you post a screenshot with F3 open, im wondering if this is common to a JVM version or something... as i still cant reproduce it, under any install.

**Comment by trey-k** [comment] 2020-07-30 22:25
![2020-07-30_15 17 59](https://user-images.githubusercontent.com/10183408/88980577-dd5d2900-d278-11ea-82cd-a2e8c012637a.png)

**Comment by Buttplucc** [comment] 2020-07-30 22:53
![2020-07-30_15 52 08](https://user-images.githubusercontent.com/69018166/88982338-d801dd80-d27c-11ea-87b7-a786277e8ec4.png)

**Comment by Flanks255** [comment] 2020-07-30 23:23
assuming screret also has optifine, id say we found our problem, optifine is doing something to the lighting system, at least i have a lead now... i tried downloading optifine, and sure enough, they stop working...

**Comment by Buttplucc** [comment] 2020-07-31 01:11
thank you for figuring that out. will there be a fix for this or will i have to uninstall optifine?

**Comment by screret** [comment] 2020-07-31 05:32
oh yea i have optifine

**Comment by Flanks255** [comment] 2020-07-31 20:38
Fixed in 1.0.1(bb927de)

**Closed by Flanks255** 2020-07-31 20:38 UTC
